# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
- name: Build
  run: |
    npm install
    npm run build

- name: Deploy to Azure Web App
  uses: azure/webapps-deploy@v3
  with:
    app-name: eazyweek-beta-web
    publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
    package: .
